import { BlogPost, Campaign, Category, Donation, User } from '../types';

// Sample categories
export const categories: Category[] = [
  {
    id: '1',
    name: 'Technology',
    slug: 'technology',
    description: 'Innovative tech projects and gadgets',
    icon: 'cpu',
  },
  {
    id: '2',
    name: 'Arts',
    slug: 'arts',
    description: 'Creative artistic endeavors and cultural projects',
    icon: 'palette',
  },
  {
    id: '3',
    name: 'Community',
    slug: 'community',
    description: 'Projects that benefit local communities',
    icon: 'users',
  },
  {
    id: '4',
    name: 'Education',
    slug: 'education',
    description: 'Learning initiatives and educational resources',
    icon: 'book-open',
  },
  {
    id: '5',
    name: 'Environment',
    slug: 'environment',
    description: 'Eco-friendly and sustainable projects',
    icon: 'leaf',
  },
  {
    id: '6',
    name: 'Health',
    slug: 'health',
    description: 'Medical research and wellness projects',
    icon: 'heart-pulse',
  },
];

// Sample users
export const users: User[] = [
  {
    id: '1',
    name: 'Alex Morgan',
    email: 'alex@example.com',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150',
    bio: 'Tech enthusiast and social entrepreneur',
    createdAt: new Date('2023-05-10'),
  },
  {
    id: '2',
    name: 'Jamie Smith',
    email: 'jamie@example.com',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
    bio: 'Artist and community organizer',
    createdAt: new Date('2023-06-15'),
  },
  {
    id: '3',
    name: 'Taylor Reed',
    email: 'taylor@example.com',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
    bio: 'Environmental advocate and writer',
    createdAt: new Date('2023-04-22'),
  },
];

// Sample campaigns
export const campaigns: Campaign[] = [
  {
    id: '1',
    title: 'EcoCharge: Solar Power Bank',
    description: 'A sustainable power bank that charges with solar energy',
    story: 'Our journey began with a simple idea: create a power bank that\'s not just powerful but also sustainable. The EcoCharge harnesses solar energy to power your devices anywhere, reducing reliance on grid electricity and lowering your carbon footprint. Made from recycled materials and designed for durability, this power bank represents the future of sustainable tech accessories.',
    goal: 25000,
    currentAmount: 18750,
    category: 'Technology',
    tags: ['eco-friendly', 'solar', 'gadgets'],
    coverImage: 'https://images.pexels.com/photos/6970075/pexels-photo-6970075.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creatorId: '1',
    endDate: new Date('2023-12-31'),
    status: 'active',
    createdAt: new Date('2023-07-15'),
    updatedAt: new Date('2023-07-15'),
  },
  {
    id: '2',
    title: 'Community Art Gallery Renovation',
    description: 'Help us renovate our local art gallery to showcase more artists',
    story: 'Our community art gallery has been a cornerstone of local culture for over 20 years. Now, we\'re embarking on an ambitious renovation project to expand our exhibition space, improve accessibility, and create new programs for emerging artists. Your support will help us build a more vibrant creative hub that can inspire future generations.',
    goal: 50000,
    currentAmount: 32000,
    category: 'Arts',
    tags: ['community', 'art', 'renovation'],
    coverImage: 'https://images.pexels.com/photos/20967/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creatorId: '2',
    endDate: new Date('2023-11-30'),
    status: 'active',
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2023-06-15'),
  },
  {
    id: '3',
    title: 'GreenSpace: Urban Garden Initiative',
    description: 'Creating community gardens in urban neighborhoods',
    story: 'GreenSpace aims to transform vacant urban lots into thriving community gardens. We believe everyone should have access to fresh produce and green spaces regardless of their neighborhood. Our program includes garden construction, education workshops, and community events to build sustainable food systems and stronger neighborhood connections.',
    goal: 35000,
    currentAmount: 28000,
    category: 'Environment',
    tags: ['gardening', 'community', 'sustainability'],
    coverImage: 'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creatorId: '3',
    endDate: new Date('2023-10-15'),
    status: 'active',
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date('2023-05-25'),
  },
  {
    id: '4',
    title: 'Digital Literacy for Seniors',
    description: 'Teaching seniors essential digital skills for the modern world',
    story: 'In today\'s increasingly digital world, many seniors risk being left behind without proper technology skills. Our program provides personalized training sessions, user-friendly guides, and ongoing support to help seniors navigate everything from video calls with family to online banking and healthcare portals. We believe digital literacy is a right, not a privilege.',
    goal: 15000,
    currentAmount: 9500,
    category: 'Education',
    tags: ['seniors', 'technology', 'education'],
    coverImage: 'https://images.pexels.com/photos/7551617/pexels-photo-7551617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creatorId: '1',
    endDate: new Date('2023-09-30'),
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2023-06-05'),
  },
];

// Sample donations
export const donations: Donation[] = [
  {
    id: '1',
    amount: 100,
    campaignId: '1',
    userId: '2',
    name: 'Jamie Smith',
    message: 'Love this idea! Can\'t wait to see it happen.',
    isAnonymous: false,
    createdAt: new Date('2023-07-20'),
  },
  {
    id: '2',
    amount: 500,
    campaignId: '1',
    name: 'Anonymous',
    isAnonymous: true,
    createdAt: new Date('2023-07-25'),
  },
  {
    id: '3',
    amount: 250,
    campaignId: '2',
    userId: '3',
    name: 'Taylor Reed',
    message: 'Art is essential for our community!',
    isAnonymous: false,
    createdAt: new Date('2023-06-18'),
  },
  {
    id: '4',
    amount: 75,
    campaignId: '3',
    userId: '1',
    name: 'Alex Morgan',
    message: 'Looking forward to seeing more green spaces!',
    isAnonymous: false,
    createdAt: new Date('2023-05-29'),
  },
];

// Sample blog posts
export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'From Idea to Impact: How EcoCharge Is Changing Lives',
    content: 'The EcoCharge Solar Power Bank started as a vision to create sustainable technology accessible to everyone. Today, it\'s being used in remote villages to power essential medical devices and educational tools. This success story showcases how a simple idea, with community support, can create ripples of positive change across the globe.',
    excerpt: 'How a sustainable power bank is bringing electricity to remote communities...',
    coverImage: 'https://images.pexels.com/photos/9875441/pexels-photo-9875441.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    author: 'Editorial Team',
    authorId: '1',
    createdAt: new Date('2023-08-05'),
    updatedAt: new Date('2023-08-05'),
  },
  {
    id: '2',
    title: 'Community Art Gallery: A Second Home for Local Youth',
    content: 'When the Community Art Gallery renovation began, nobody expected it would become a sanctuary for at-risk youth in the area. Through specialized programs and mentorship opportunities, dozens of teenagers have found their creative voice and purpose. This is the story of how art spaces can transform not just buildings, but lives.',
    excerpt: 'How a renovated art gallery became a haven for creative expression...',
    coverImage: 'https://images.pexels.com/photos/1268558/pexels-photo-1268558.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    author: 'Melissa Chen',
    authorId: '2',
    createdAt: new Date('2023-07-15'),
    updatedAt: new Date('2023-07-20'),
  },
  {
    id: '3',
    title: 'Growing Resilience: Urban Gardens Feed Families During Crisis',
    content: 'When economic hardship hit our city, the GreenSpace urban gardens became more than beautiful community spaces—they became essential food sources for dozens of families. This article explores how community-supported agriculture provides both nutritional and emotional sustenance during challenging times.',
    excerpt: 'How urban gardens are providing food security and hope...',
    coverImage: 'https://images.pexels.com/photos/7728082/pexels-photo-7728082.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    author: 'Jordan Williams',
    authorId: '3',
    createdAt: new Date('2023-06-22'),
    updatedAt: new Date('2023-06-25'),
  },
];